# Generated by Django 2.2 on 2020-09-27 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='destincountry',
            field=models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.CASCADE, to='agency.Destination'),
            preserve_default=False,
        ),
    ]
