# Generated by Django 2.2 on 2020-10-10 23:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_reviews_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
