# Generated by Django 2.2 on 2020-09-27 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20200927_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='destincountry',
        ),
        migrations.AddField(
            model_name='destination',
            name='destincountry',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Country'),
            preserve_default=False,
        ),
    ]
