# Generated by Django 2.2 on 2020-10-12 11:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20201012_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
