# Generated by Django 2.2 on 2020-10-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20201012_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mac', models.CharField(max_length=1000)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Destination')),
            ],
        ),
    ]
