# Generated by Django 2.2 on 2020-11-08 08:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
