# Generated by Django 2.2 on 2020-11-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_destination_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mac', models.CharField(max_length=1000)),
                ('total', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('receipt_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_method', models.CharField(default='Other', max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('dest', models.ManyToManyField(blank=True, to='agency.Destination')),
            ],
        ),
    ]
