# Generated by Django 2.2 on 2020-11-17 23:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_auto_20201118_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookeddest',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Destination'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='dest',
        ),
        migrations.AddField(
            model_name='cart',
            name='dest',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Destination'),
            preserve_default=False,
        ),
    ]
