# Generated by Django 2.2 on 2020-11-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_auto_20201118_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='dest',
        ),
        migrations.AddField(
            model_name='cart',
            name='dest',
            field=models.ManyToManyField(to='agency.Destination'),
        ),
    ]
