# Generated by Django 2.2 on 2020-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_auto_20201118_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_mac',
            field=models.CharField(default='empty', max_length=1000),
        ),
    ]
